del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Profile 1\Extension Rules\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Profile 1\Extension Scripts\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Profile 1\Extension State\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Profile 1\Extension State\LOG.old"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Profile 1\Extensions"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Default\Extension Rules\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Default\Extension Scripts\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Default\Extension State\CURRENT"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Default\Extension State\LOG.old"
del "C:\Users\252454\AppData\Local\Google\Chrome\User Data\Default\Extensions"