del "%localappdata%\Google\Chrome\User Data\Profile 1\Extension Rules\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Profile 1\Extension Scripts\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Profile 1\Extension State\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Profile 1\Extension State\LOG.old"
del "%localappdata%\Google\Chrome\User Data\Profile 1\Extensions"
del "%localappdata%\Google\Chrome\User Data\Default\Extension Rules\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Default\Extension Scripts\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Default\Extension State\CURRENT"
del "%localappdata%\Google\Chrome\User Data\Default\Extension State\LOG.old"
del "%localappdata%\Google\Chrome\User Data\Default\Extensions"
md "%localappdata%\Google\Chrome\User Data\Profile 1\Extensions"
md "%localappdata%\Google\Chrome\User Data\Default\Extensions"
